In [2]:
import numpy as np

a = np.array([1, 2, 3])   # Create a rank 1 array

In [4]:
a.dtype

dtype('int32')

In [ ]:
##https://zhuanlan.zhihu.com/p/39287693 讲解 numpy axis 和shape 的使用心法

In [ ]:
#切片的使用心法

In [14]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]])
print(a.shape)
# 从某个索引处开始切割
print('从数组索引 a[1:] 处开始切割')
print(a[1:])

(3, 3)
从数组索引 a[1:] 处开始切割
[[3 4 5]
 [4 5 6]]


In [11]:
# int8, int16, int32, int64 四种数据类型可以使用字符串 'i1', 'i2','i4','i8' 代替
persontype = np.dtype({'names':['name','age','chinese','math','english'],
           'formats':['S32','i','i','i','f']})
peoples = np.array([("zhangFei",32,75,100,90),("GuanYu",24,85,96,88.5),
                    ("zhaoYun",28,85,92,96.5),("HuangZhong",29,65,85,100)],dtype=persontype)

In [15]:
peoples.shape

(4,)

In [20]:
ages = peoples[:]['age'] ## person 为1为数组 peoples[:] 表示取整行
ages

array([32, 24, 28, 29], dtype=int32)

In [ ]:
### 连续数组的创建
x1 = np.arrange(1,11,2)  ##参数说明 初值，终值，步长，默认不包含终值
x2 = np.linspace(1,9,5)  ##参数说明 初始值，终值，元素个数，默认包含终值

In [22]:
###统计函数
a = np.array([[1,2,3],[4,5,6]])
a.shape

(2, 3)

In [23]:
###最大值，最小值类似
print(np.amin(a,0))  ### axis=0, 参考 https://zhuanlan.zhihu.com/p/39287693

[1 2 3]


In [25]:
##统计数组的百分位数 percentlie
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(np.percentile(a, 50))  ##percentile 的第二个参数从0-100，为50 表示平均值，100为最大值
print(np.percentile(a, 50, axis=0))
print(np.percentile(a, 50, axis=1))


5.0
[4. 5. 6.]
[2. 5. 8.]


In [27]:
###平均值mean(), 和中位数 median()
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
# 求中位数
print(np.median(a))
print(np.median(a, axis=0))
print(np.median(a, axis=1))
# 求平均数
print(np.mean(a))
print(np.mean(a, axis=0))
print(np.mean(a, axis=1))


5.0
[4. 5. 6.]
[2. 5. 8.]
5.0
[4. 5. 6.]
[2. 5. 8.]


In [28]:
###average 平均值
a = np.array([1,2,3,4])
wts = np.array([1,2,3,4])
print(np.average(a,weights=wts)) #(1*1+2*2+3*3+4*4)/(1+2+3+4)=3.0

3.0


In [29]:
####标准差和偏差 （标准差 std, 方差 var）方差=mean((x - x.mean())** 2)
a = np.array([1,2,3,4])
print(np.std(a))
print(np.var(a)) ## 方差的定义： 

In [30]:
### 排序  sort(a, axis=-1, kind=‘quicksort',order=None)
a = np.array([[4,3,2],[2,4,1]])
print(np.sort(a,axis=1))

[[2 3 4]
 [1 2 4]]


In [41]:
###练习
persontype = np.dtype({'names':['name','chinese','english','math','total'],
           'formats':['S32','i','i','i','i']})
peoples = np.array([("zhangFei",66,65,30,0),("GuanYu",95,85,98,0),
                    ("zhaoYun",93,92,96,0),("HuangZhong",90,88,77,0),("DianWei",80,90,90,0)],dtype=persontype)

In [42]:
row_name = peoples.dtype.names

In [43]:
for row_name in row_name:
    if row_name is "name":
        continue
    print("mean of {}:{}".format(row_name,peoples[row_name].mean()))

mean of chinese:84.8
mean of english:84.0
mean of math:78.2
mean of total:0.0


In [44]:
###求总成绩之和，然后输出总分最高的, 增加一列
peoples[:]['total'] = peoples[:]['chinese']+peoples[:]['english']+peoples[:]['math']

In [45]:
peoples

array([(b'zhangFei', 66, 65, 30, 161), (b'GuanYu', 95, 85, 98, 278),
       (b'zhaoYun', 93, 92, 96, 281), (b'HuangZhong', 90, 88, 77, 255),
       (b'DianWei', 80, 90, 90, 260)],
      dtype=[('name', 'S32'), ('chinese', '<i4'), ('english', '<i4'), ('math', '<i4'), ('total', '<i4')])

In [46]:
np.sort(peoples,order="total")

array([(b'zhangFei', 66, 65, 30, 161), (b'HuangZhong', 90, 88, 77, 255),
       (b'DianWei', 80, 90, 90, 260), (b'GuanYu', 95, 85, 98, 278),
       (b'zhaoYun', 93, 92, 96, 281)],
      dtype=[('name', 'S32'), ('chinese', '<i4'), ('english', '<i4'), ('math', '<i4'), ('total', '<i4')])